### ISSUE TITLE
Big extension of your code, should I fork it or do you care to have it?

### ISSUE THREAD

**Issue by reptilex** [bessarabov/animated-consumption-card#4]
Hey, thanks for the card. It wasn't quite what I wanted so I created a big extension based on yours. It's not very tidy yet but it enables  5 icons and the paths with circles for solar panel, grid, house, battery and car. The two last ones are optional and depend on some entities being there. It's a bit nearer to what the tesla app shows. 
Do you care to check it out and maybe extend yours or should I just fork it and mention you? It's a bit more complex than yours and there might be still some issues. Just let me know.

**Comment by reptilex** [comment]
you can check it out [here](https://github.com/reptilex/homeassistantconfig/blob/master/config/www/tesla-style-solar-power-card.js) on my config github repo

**Comment by bessarabov** [comment]
Wow! It sounds amazing!

Actually I'm not a great fan of forks, but my first impression is that it is better to release that card by yourself. I'm afraid that we will spend too much time discussing it an I'm not sure that we have the same vision for the card. I don't want to delay the release of your card.

I'm really happy that you have taken some of my work as a base. And thank your for asking this question in advance.

I think that you should create repo
tesla-style-solar-power-card (just a new repo, not even using github fork feature) and place your work there.

**Comment by reptilex** [comment]
Great, I will do so. It was a big help starting of on your code. Thanks again.
