### ISSUE TITLE
Did this get pulled form HACS?  Not seeing it in there

### ISSUE THREAD

**Issue by fireheadman** [bessarabov/animated-consumption-card#5]
Please update the README info if this is no longer in HACS....
If it is in HACS, can you please let me know how to search for it.
Nothing comes up under "consumption" or "animated"

**Comment by bessarabov** [comment]
"animated-consumption-card" was never in the HACS by default. But is can be installed with HACS if you add this repo to the HACS.

Here is a screenshot from [README.md](https://github.com/bessarabov/animated-consumption-card/blob/master/README.md):

![Screenshot 2020-11-09 at 07 27 31](https://user-images.githubusercontent.com/47263/98500303-30258400-225d-11eb-871c-907c55d4ea49.png)
